# Generated by Django 4.1.5 on 2023-02-24 12:54

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=27, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_worker', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=27, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, choices=[('Github', 'Github'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Website', 'Website')], max_length=20)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=28, primary_key=True, serialize=False, unique=True)),
                ('skill', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, null=True)),
                ('bio', models.TextField(null=True)),
                ('slug', models.SlugField()),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('links', models.ManyToManyField(blank=True, related_name='profile_link', to='account.link')),
                ('skills', models.ManyToManyField(blank=True, to='account.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
