version: '3.9'
services:
  db:
    image: postgres:12-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/src/.env

volumes:
  postgres_data: