# Generated by Django 4.1.5 on 2023-02-26 16:51

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('about', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.category')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('course_discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='LikeReply',
            fields=[
                ('likereply_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=27, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=28, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='course_video')),
                ('locked', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_syllabus', to='course.course')),
                ('syllabus_quiz', models.ManyToManyField(blank=True, related_name='my_quiz', to='course.quiz')),
                ('topics', models.ManyToManyField(blank=True, to='course.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=28, primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skill_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skil_cours', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField(default=1)),
                ('comment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cours', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=28, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reply', to='course.answer')),
                ('like_reply', models.ManyToManyField(blank=True, related_name='like_reply_me', through='course.LikeReply', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=400)),
                ('detail', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(blank=True, to='course.answer')),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='likereply',
            name='reply_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reaction', to='course.reply'),
        ),
        migrations.AddField(
            model_name='likereply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LikeAnswer',
            fields=[
                ('likeanswer_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reaction', to='course.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('isLead_instructor', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('faq_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_cours', to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='questions',
            field=models.ManyToManyField(blank=True, to='course.question'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEnrolled', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('enroll_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reply_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reaction', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='course_enroll', through='course.CourseEnroll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='my_faq', to='course.faq'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, to='course.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='my_review', to='course.reviews'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='my_skills', to='course.skills'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ManyToManyField(blank=True, to='course.syllabus'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='like_answer',
            field=models.ManyToManyField(blank=True, related_name='like_me', through='course.LikeAnswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='reply',
            field=models.ManyToManyField(blank=True, to='course.reply'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
