# Generated by Django 4.1.5 on 2023-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_discussion_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='questions',
            field=models.ManyToManyField(blank=True, to='course.question'),
        ),
    ]
