# Generated by Django 4.1.5 on 2023-02-28 11:52

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_discussion_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('quizattempt_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=34, primary_key=True, serialize=False, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('quizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
