# Generated by Django 4.1.5 on 2023-02-28 12:18

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('option', models.CharField(max_length=500)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.options')),
                ('questionz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('quizattempt_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=34, primary_key=True, serialize=False, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('quizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
