# Generated by Django 4.1.5 on 2023-03-02 11:44

import customshortuuidfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=17, primary_key=True, serialize=False, unique=True)),
                ('option', models.CharField(max_length=500)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('questopt_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=19, primary_key=True, serialize=False, unique=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.option')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('quizs', models.ManyToManyField(blank=True, to='quiz.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=19, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
