# Generated by Django 4.1.5 on 2023-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='opt',
            field=models.ManyToManyField(blank=True, to='quiz.option'),
        ),
    ]
