# Generated by Django 4.1.5 on 2023-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_option_question_question_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizs',
            field=models.ManyToManyField(blank=True, related_name='my_quiz', to='quiz.question'),
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
