# Generated by Django 4.1.5 on 2023-03-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_quizs_delete_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
    ]
