# Generated by Django 4.1.5 on 2023-03-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_option_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
