# Generated by Django 4.1.5 on 2023-03-03 11:18

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_alter_option_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempter',
            fields=[
                ('attempter_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
