# Generated by Django 4.1.5 on 2023-03-03 17:17

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_question_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.CreateModel(
            name='AttemtQuestion',
            fields=[
                ('question_id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=19, primary_key=True, serialize=False, unique=True)),
                ('answered', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
